name = "cloudflare-error-1101"
compatibility_date = "2021-11-12"
send_metrics = false
pages_build_output_dir = ".svelte-kit/cloudflare"

compatibility_flags = ["nodejs_compat"]

[vars]
NODE_VERSION = "20.9.0"
PNPM_VERSION = "9"
